# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too

aliases:
  - &filter-only-master
    branches:
      only:
        - master

version: 2.1
jobs:
  deploy-website:
    docker:
      # specify the version of Node you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      # Right now, this just tests that we can build on CircleCI.
      # After we go live, replace `yarn build` below with `yarn run publish-gh-pages`
      # to have CircleCI automatically build and publish to the `gh-pages` branch.
      - run:
          name: Deploying Libra Website to GitHub Pages
          command: |
            git config --global user.email "libra-doc-bot@users.noreply.github.com"
            git config --global user.name "Libra Website Deployment Script"
            echo "machine github.com login libra-doc-bot password $PUBLISH_WEBSITE_TOKEN" > ~/.netrc
            ./scripts/build_docs.sh -b
            cd website
            GIT_USER=libra-doc-bot USE_SSH=false yarn run publish-gh-pages

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - deploy-website:
        filters: *filter-only-master
